"""All database access goes through a repository.

- SupabaseRepository: the real database (Supabase Postgres, tables from supabase/schema.sql).
- InMemoryRepository: a Python dict. Used by tests, and as a fallback when Supabase is not
  configured (data is then lost when the server restarts).

Rows are flat dicts whose keys are the silage_samples column names.
"""

import logging
from datetime import datetime
from functools import lru_cache
from typing import Any, Protocol

from app.config import get_settings

log = logging.getLogger(__name__)

Row = dict[str, Any]


class SampleRepository(Protocol):
    name: str

    def get_sample(self, sample_id: str) -> Row | None: ...

    def save_sample(self, row: Row) -> Row:
        """Insert the sample, or update it if the sample_id already exists. Returns the stored row."""
        ...

    def touch_device(self, device_id: str, seen_at: datetime) -> None:
        """Record that a device has just been seen (creates the device row if new)."""
        ...


class InMemoryRepository:
    name = "memory"

    def __init__(self) -> None:
        self.samples: dict[str, Row] = {}
        self.devices: dict[str, Row] = {}
        self._next_id = 1

    def get_sample(self, sample_id: str) -> Row | None:
        row = self.samples.get(sample_id)
        return dict(row) if row else None

    def save_sample(self, row: Row) -> Row:
        stored = dict(row)
        existing = self.samples.get(stored["sample_id"])
        if existing:
            stored["id"] = existing["id"]
        else:
            stored["id"] = self._next_id
            self._next_id += 1
        self.samples[stored["sample_id"]] = stored
        return dict(stored)

    def touch_device(self, device_id: str, seen_at: datetime) -> None:
        device = self.devices.setdefault(device_id, {"device_id": device_id, "pending_sync": 0})
        device["last_seen_at"] = seen_at


class SupabaseRepository:
    name = "supabase"

    def __init__(self, url: str, service_key: str) -> None:
        from supabase import create_client  # imported here so tests never need a connection

        self.client = create_client(url, service_key)

    @staticmethod
    def _to_json(row: Row) -> Row:
        # "id" is generated by the database and must never be sent back.
        return {
            key: value.isoformat() if isinstance(value, datetime) else value
            for key, value in row.items()
            if key != "id"
        }

    def get_sample(self, sample_id: str) -> Row | None:
        result = self.client.table("silage_samples").select("*").eq("sample_id", sample_id).limit(1).execute()
        return result.data[0] if result.data else None

    def save_sample(self, row: Row) -> Row:
        result = self.client.table("silage_samples").upsert(self._to_json(row), on_conflict="sample_id").execute()
        return result.data[0]

    def touch_device(self, device_id: str, seen_at: datetime) -> None:
        payload = {"device_id": device_id, "last_seen_at": seen_at.isoformat()}
        self.client.table("silage_devices").upsert(payload, on_conflict="device_id").execute()


@lru_cache
def get_repository() -> SampleRepository:
    """FastAPI dependency. Tests replace it with an InMemoryRepository."""
    settings = get_settings()
    if settings.supabase_enabled:
        return SupabaseRepository(settings.supabase_url, settings.supabase_service_key)
    log.warning("SUPABASE_URL / SUPABASE_SERVICE_KEY not set: using in-memory storage (data is lost on restart)")
    return InMemoryRepository()
